development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobpsahni
  password: 24db126b-d683-4e1c-a1dd-0347a4b15344
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username:
  password:
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true